<style>
.snatch-hub{max-width:1240px;color:var(--theme-text,#e5e7eb)}
.snatch-overview{background:var(--theme-surface,#17202d);border:1px solid var(--theme-border,#334155);border-radius:16px;margin-bottom:20px;box-shadow:0 6px 20px var(--theme-shadow,rgba(0,0,0,.08));overflow:hidden}
.snatch-heading{display:flex;align-items:center;justify-content:space-between;gap:24px;padding:24px;margin:0}
.snatch-eyebrow{color:var(--theme-muted,#94a3b8);font-size:13px;letter-spacing:.06em;margin-bottom:8px}
.snatch-heading h1{font-size:clamp(1.65rem,3vw,2.25rem);font-weight:750;margin:0 0 8px;letter-spacing:-.03em}
.snatch-heading p{color:var(--theme-muted,#94a3b8);margin:0;max-width:700px;font-size:13px;line-height:1.7}
.snatch-count{display:flex;flex-direction:column;align-items:center;min-width:100px;padding:14px 24px;border:1px solid var(--theme-border,#334155);border-radius:16px;background:var(--theme-surface-alt,#202c3d)}
.snatch-count strong{font-size:1.8rem;line-height:1.2}.snatch-count span{font-size:13px;color:var(--theme-muted,#94a3b8)}
.snatch-tabs{display:flex;flex-wrap:wrap;gap:6px;padding:7px;background:var(--theme-surface,#17202d);border:1px solid var(--theme-border,#334155);border-radius:14px;margin-bottom:22px}
.snatch-tabs a{display:flex;align-items:center;gap:8px;padding:10px 14px;border-radius:9px;text-decoration:none;color:var(--theme-muted,#94a3b8);font-size:.9rem;font-weight:600}
.snatch-tabs a:hover{background:var(--theme-surface-alt,#202c3d);color:var(--theme-text,#e5e7eb)}
.snatch-tabs a.is-current{background:var(--theme-blue-soft,rgba(59,130,246,.15));color:var(--theme-blue-text,#93c5fd)}
.snatch-list-heading{display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:12px 20px;font-size:13px;line-height:1.6;color:var(--theme-text,#e5e7eb);padding:15px 24px;border-top:1px solid var(--theme-border,#334155);background:var(--theme-surface-alt,#202c3d)}
.snatch-list-heading>span{display:flex;align-items:center;gap:8px}.snatch-list-heading i{color:var(--theme-blue-text,#93c5fd);flex-shrink:0}.snatch-summary-target{color:var(--theme-muted,#94a3b8)}
.snatch-list{display:grid;gap:18px}.snatch-entry{border:1px solid var(--theme-border,#334155);border-left:3px solid var(--theme-border,#334155);border-radius:16px;background:var(--theme-surface,#17202d);padding:20px;box-shadow:0 6px 20px var(--theme-shadow,rgba(0,0,0,.08));overflow:hidden}
.snatch-entry-success{border-left-color:var(--theme-green-text,#4ade80)}.snatch-entry-danger{border-left-color:var(--theme-red-text,#f87171)}.snatch-entry-info{border-left-color:var(--theme-blue-text,#93c5fd)}
.snatch-entry-top{display:flex;align-items:flex-start;justify-content:space-between;gap:18px}
.snatch-torrent{display:flex;gap:14px;min-width:0}.snatch-torrent>div:last-child{min-width:0}.snatch-file-icon{display:flex;align-items:center;justify-content:center;flex:0 0 44px;height:48px;border-radius:12px;background:var(--theme-blue-soft,rgba(59,130,246,.12));color:var(--theme-blue-text,#93c5fd);font-size:1.35rem}
.snatch-entry-label{font-size:13px;color:var(--theme-muted,#94a3b8);margin-bottom:5px}.snatch-entry h2{font-size:1.05rem;line-height:1.5;font-weight:650;margin:0;overflow-wrap:anywhere}.snatch-entry h2 a{color:var(--theme-text,#e5e7eb);text-decoration:none}.snatch-entry h2 a:hover{text-decoration:underline}
.snatch-dates{display:flex;flex-wrap:wrap;gap:6px 18px;margin-top:8px;font-size:13px;color:var(--theme-muted,#94a3b8)}
.snatch-status{display:inline-flex;align-items:center;gap:6px;border-radius:20px;padding:6px 11px;font-size:13px;white-space:nowrap;background:var(--theme-surface-alt,#202c3d);color:var(--theme-muted,#94a3b8)}
.snatch-status-success{background:var(--theme-green-soft,rgba(34,197,94,.12));color:var(--theme-green-text,#4ade80)}.snatch-status-danger{background:var(--theme-red-soft,rgba(239,68,68,.12));color:var(--theme-red-text,#f87171)}.snatch-status-info{background:var(--theme-blue-soft,rgba(59,130,246,.12));color:var(--theme-blue-text,#93c5fd)}
.snatch-metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px;margin:16px 0;padding:14px 0;border-top:1px solid var(--theme-border,#334155);border-bottom:1px solid var(--theme-border,#334155)}
.snatch-metrics dt{font-weight:400;font-size:13px;color:var(--theme-muted,#94a3b8);margin-bottom:5px}.snatch-metrics dt i{margin-right:4px}.snatch-metrics dd{font-weight:650;font-size:1.1rem;margin:0 0 4px;overflow-wrap:anywhere}.snatch-metrics small{font-size:13px;color:var(--theme-muted,#94a3b8)}
.snatch-progress-grid{display:grid;grid-template-columns:1fr 1fr;gap:24px}.snatch-progress-label{display:flex;justify-content:space-between;gap:10px;font-size:13px;margin-bottom:8px;color:var(--theme-muted,#94a3b8)}.snatch-progress-label strong{font-weight:600;color:var(--theme-text,#e5e7eb)}
.snatch-progress{height:6px;border-radius:10px;background:var(--theme-surface-alt,#263448);overflow:hidden}.snatch-progress span{display:block;height:100%;border-radius:10px;background:var(--theme-green-text,#4ade80)}.snatch-progress-download span{background:var(--theme-blue-text,#93c5fd)}
.snatch-guidance{display:flex;align-items:flex-start;gap:9px;margin-top:20px;font-size:13px;color:var(--theme-muted,#94a3b8);line-height:1.6}.snatch-guidance-warning{color:var(--theme-amber-text,#facc15)}.snatch-deadline{display:block;font-size:13px}
.snatch-announce{display:flex;align-items:center;flex-wrap:wrap;gap:6px 10px;margin-top:15px;padding:12px 14px;background:var(--theme-surface-alt,#202c3d);border-radius:10px;font-size:13px}.snatch-announce>i{color:var(--theme-blue-text,#93c5fd)}.snatch-muted{color:var(--theme-muted,#94a3b8)}.snatch-event{padding:2px 8px;border:1px solid var(--theme-border,#334155);border-radius:6px;font-size:13px}
.snatch-actions{display:flex;align-items:center;flex-wrap:wrap;gap:10px;margin-top:18px;padding-top:16px;border-top:1px solid var(--theme-border,#334155)}.snatch-actions form{margin:0!important}.snatch-actions .btn{font-size:13px;border-radius:8px;padding:8px 12px}
.snatch-empty{text-align:center;padding:60px 24px;border:1px dashed var(--theme-border,#334155);border-radius:16px;background:var(--theme-surface,#17202d)}.snatch-empty>i{font-size:2rem;color:var(--theme-muted,#94a3b8)}.snatch-empty h2{font-size:1.15rem;margin:16px 0 8px}.snatch-empty p{color:var(--theme-muted,#94a3b8);font-size:.9rem;margin:0}.snatch-pagination{display:flex;justify-content:center;margin-top:28px}
.snatch-hub a:focus-visible,.snatch-hub button:focus-visible{outline:2px solid var(--theme-blue-text,#93c5fd);outline-offset:3px}
@media(max-width:767px){.snatch-entry{padding:18px}.snatch-metrics{grid-template-columns:1fr 1fr}.snatch-progress-grid{grid-template-columns:1fr;gap:16px}.snatch-entry-top{flex-wrap:wrap}.snatch-entry-controls{margin-left:58px}.snatch-count{min-width:76px;padding:12px}.snatch-tabs a{padding:9px 10px;font-size:13px}.snatch-heading{gap:14px;padding:18px;align-items:flex-start}.snatch-heading>div:first-child{min-width:0;overflow-wrap:anywhere}.snatch-list-heading{padding:14px 18px;flex-direction:column;align-items:flex-start}.snatch-announce{align-items:flex-start}}
@media(prefers-reduced-motion:reduce){.snatch-hub *{scroll-behavior:auto!important}}
.snatch-search{display:flex;align-items:flex-end;flex-wrap:wrap;gap:12px;padding:18px 20px;margin-bottom:20px;border:1px solid var(--theme-border,#334155);border-radius:14px;background:var(--theme-surface,#17202d);font-size:13px}
.snatch-search-field{flex:1 1 260px}.snatch-search label{display:block;font-weight:600;margin-bottom:8px}.snatch-search .form-control{font-size:13px;background:var(--theme-surface-alt,#202c3d);color:var(--theme-text,#e5e7eb);border-color:var(--theme-border,#334155)}.snatch-search .form-control::placeholder{color:var(--theme-muted,#94a3b8)}.snatch-search .btn{font-size:13px}.snatch-search p{flex-basis:100%;margin:0;line-height:1.6;color:var(--theme-muted,#94a3b8)}
.snatch-entry-controls{display:flex;align-items:center;justify-content:flex-end;flex-wrap:wrap;gap:8px;flex-shrink:0}.snatch-delete-form{margin:0}.snatch-delete-form .btn{font-size:13px;padding:6px 10px;border-radius:8px;white-space:nowrap}.snatch-owner{display:inline-flex;align-items:center;gap:6px;padding:6px 11px;border-radius:20px;font-size:13px;background:var(--theme-blue-soft,rgba(59,130,246,.12));color:var(--theme-blue-text,#93c5fd)}
@media(max-width:767px){.snatch-entry-controls{justify-content:flex-start;flex-shrink:1}}
</style>
