<style>
.discussion{--discussion-border:var(--ui-border,#2a384b);--discussion-accent:var(--ui-accent,#2dd4bf);background:linear-gradient(145deg,#0f1722,#0a1019);border:1px solid var(--discussion-border);border-radius:18px;color:#e7edf5;padding:26px;overflow:hidden}
.discussion-heading{display:flex;justify-content:space-between;gap:16px;margin-bottom:24px}.discussion-eyebrow{font-size:10px;letter-spacing:2px;color:var(--discussion-accent);font-weight:700}.discussion-heading h3{font-size:23px;font-weight:700;margin:7px 0}.discussion-heading h3 span{font-size:12px;vertical-align:middle;background:#18222f;border-radius:20px;padding:4px 9px}.discussion-heading p,.discussion-empty p{color:#a4b2c5;font-size:13px;margin:0}.discussion-heading>i{font-size:30px;color:var(--discussion-accent)}
.discussion-composer{background:#0b121c;border:1px solid var(--discussion-border);border-radius:12px;padding:16px;margin-bottom:24px}.discussion-composer label{font-size:14px;font-weight:600;display:block;margin-bottom:12px}.discussion-composer label span{color:#a4b2c5;font-weight:400;font-size:12px;margin-left:5px}.discussion-toolbar{display:flex;flex-wrap:wrap;gap:5px;margin-bottom:8px}.discussion-toolbar button{background:transparent;color:#b8c7da;border:0;padding:5px 9px;border-radius:5px;font-size:12px}.discussion textarea{display:block;width:100%;background:#080e17;color:#edf3fb;border:1px solid var(--discussion-border);border-radius:8px;padding:12px;resize:vertical;min-height:90px;font-size:14px}.discussion textarea::placeholder{color:#8799b0}.discussion-composer footer{display:flex;flex-wrap:wrap;align-items:center;justify-content:space-between;gap:12px;margin-top:12px}.discussion-composer small{font-size:11px;color:#9cadc1}.discussion-submit{background:var(--discussion-accent);color:#082823;border:0;border-radius:8px;font-size:12px;font-weight:700;padding:10px 16px}.discussion button:focus-visible,.discussion summary:focus-visible,.discussion a:focus-visible,.discussion textarea:focus-visible{outline:2px solid var(--discussion-accent);outline-offset:3px}

.discussion-list{display:grid;gap:10px}
.discussion-card{padding:16px 18px;background:rgba(255,255,255,0.0126);border:1px solid var(--discussion-border);border-radius:10px;min-width:0;scroll-margin-top:90px}
.discussion-author{display:flex;align-items:center;gap:10px}
.discussion-avatar{height:34px;width:34px;flex-shrink:0;display:grid;place-items:center;border-radius:50%;background:#19272f;color:var(--discussion-accent);font-size:12px;font-weight:700;overflow:hidden}
.discussion-avatar img{width:100%;height:100%;object-fit:cover}
.discussion-identity{min-width:0}.discussion-name{display:flex;flex-wrap:wrap;gap:7px;align-items:center;overflow-wrap:anywhere}
.discussion-name a{font-weight:650;text-decoration:none;font-size:13px}.discussion-badge{font-size:9px;line-height:1.4;background:rgba(148,163,184,0.07);color:#aebed1;border-radius:4px;padding:2px 5px}
.discussion-meta{display:flex;flex-wrap:wrap;gap:5px;font-size:10px;color:#879ab1;margin-top:3px}.discussion-meta a{color:inherit;text-decoration:none}
.discussion-member-title{font-size:11px;color:#a0b1c6;margin-top:3px;overflow-wrap:anywhere}
.discussion-content{font-size:13px;line-height:1.65;margin:10px 0 12px 44px;overflow-wrap:anywhere}.discussion-content>:last-child{margin-bottom:0}.discussion-content img{max-width:100%;height:auto;border-radius:6px}.discussion-content pre{overflow:auto;max-width:100%}.discussion-content blockquote{padding:8px 12px;border-left:2px solid var(--discussion-accent);background:rgba(0,0,0,.12);margin:8px 0}
.discussion-card-footer{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-left:44px;min-height:28px}
.discussion-reaction-area{display:flex;align-items:center;gap:9px;flex-wrap:wrap}.discussion-reaction-picker{position:relative;display:flex;align-items:center;border:1px solid var(--discussion-border);border-radius:20px;background:rgba(255,255,255,0.0175)}
.discussion-card-footer form,.discussion-reaction-options form{margin:0}
.discussion-like,.discussion-reaction-toggle{border:0;background:transparent;color:#aabbd0;font-size:11px;min-height:28px}.discussion-like{border-radius:20px 0 0 20px;padding:3px 8px 3px 10px;display:flex;align-items:center;gap:5px}.discussion-like[aria-pressed=true]{color:var(--discussion-accent)}.discussion-reaction-toggle{padding:3px 8px 3px 2px;border-radius:0 20px 20px 0;font-size:9px}
.discussion-reaction-options{position:absolute;bottom:100%;left:-1px;z-index:20;display:flex;gap:3px;padding:6px;background:#17202d;border:1px solid #3a4d65;border-radius:24px;box-shadow:0 8px 24px #0006}.discussion-reaction-options[hidden]{display:none}.discussion-reaction-options button{display:grid;place-items:center;width:34px;height:34px;padding:0;border:0;border-radius:50%;background:transparent;font-size:21px;transition:transform .15s,background .15s}.discussion-reaction-options button:hover{transform:translateY(-3px);background:#222e3c}.discussion-reaction-options button[aria-pressed=true]{background:#223a3b}
.discussion-reaction-totals{display:flex;gap:7px;align-items:center;font-size:10px;color:#91a4bd}.discussion-reaction-totals>span{white-space:nowrap}
.discussion-controls{display:flex;align-items:center;justify-content:flex-end;gap:4px;margin-left:auto;flex-shrink:0}.discussion-controls button{display:flex;align-items:center;gap:4px;border:0;border-radius:5px;background:transparent;color:#91a4bd;font-size:11px;padding:5px 7px;min-height:28px;transition:background .15s,color .15s}.discussion-controls button:hover,.discussion-like:hover,.discussion-reaction-toggle:hover{background:rgba(148,163,184,0.07);color:#e2eaf5}.discussion-controls .discussion-delete:hover{color:#fda4af;background:rgba(244,63,94,.08)}.discussion-controls button span{font-size:10px;color:#7489a3}.discussion-reply-count{font-size:10px;color:#879ab1}
.discussion-form-panel .discussion-composer{margin:12px 0 0 44px}.discussion-thread{border-left:1px solid #304155;padding-left:14px;margin:14px 0 0 16px;display:grid;gap:12px}.discussion-reply{background:transparent;border:0;border-radius:0;padding:0}.discussion-reply+.discussion-reply{padding-top:12px;border-top:1px solid var(--discussion-border)}
.discussion-empty{text-align:center;padding:30px 12px}.discussion-empty>i{font-size:26px;color:var(--discussion-accent)}.discussion-empty h4{font-size:15px;margin:10px 0 6px}.discussion-notice{padding:12px;border:1px solid var(--discussion-border);background:#171f2c;border-radius:8px;margin-bottom:16px;font-size:12px}.discussion-pagination{margin-top:16px}.discussion-pagination .pagination{flex-wrap:wrap}
.discussion{padding:20px;border-radius:12px;background:#0c141e;overflow:visible}.discussion-heading{margin-bottom:16px}.discussion-heading h3{font-size:19px}.discussion-heading>i{font-size:24px}.discussion-composer{padding:12px;margin-bottom:16px;border-radius:9px}.discussion-composer label{font-size:12px;margin-bottom:8px}.discussion textarea{min-height:72px;font-size:13px}.discussion-submit{padding:8px 12px;font-size:11px}
@media(max-width:600px){.discussion{padding:12px}.discussion-card{padding:12px}.discussion-content{margin-left:0}.discussion-card-footer{margin-left:0;flex-wrap:wrap;gap:8px}.discussion-controls{gap:0}.discussion-controls button{padding:5px}.discussion-form-panel .discussion-composer{margin-left:0}.discussion-thread{margin-left:5px;padding-left:10px}.discussion-reply{padding:0}.discussion-name{gap:5px}.discussion-composer footer{align-items:stretch;flex-direction:column}.discussion-submit{width:100%}}
@media(prefers-reduced-motion:reduce){.discussion-reaction-options button,.discussion-controls button{transition:none}}
.discussion-joined{font-size:10px;color:#879ab1}
.discussion-heading h3{font-size:14px;margin:0;line-height:1.5;overflow-wrap:anywhere}.discussion-heading{margin-bottom:12px}
.discussion-composer .discussion-toolbar{display:none}.discussion-composer:focus-within .discussion-toolbar{display:flex}
.discussion-toolbar button{width:28px;height:28px;padding:4px;font-size:15px}
.discussion-reaction-status:not(:empty){font-size:11px;color:#aabbd0}
@media(hover:hover) and (pointer:fine){
 .discussion-card>.discussion-card-footer>.discussion-controls{opacity:0;pointer-events:none;transition:opacity .15s}
 .discussion-card:hover>.discussion-card-footer>.discussion-controls,.discussion-card:focus-within>.discussion-card-footer>.discussion-controls{opacity:1;pointer-events:auto}
}
.discussion-seeding{color:var(--discussion-accent);font-size:10px;display:inline-flex;align-items:center;gap:4px}.discussion-reaction-totals [data-bs-toggle="tooltip"]{cursor:help}
</style>
